version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Java is a must，or allure command can not run
    commands:
      - pip install pytest allure-pytest
      # Install Allure commandline tool (to convert json results to HTML report)
      - export ALLURE_VERSION=2.21.0
      - wget https://github.com/allure-framework/allure2/releases/download/$ALLURE_VERSION/allure-$ALLURE_VERSION.tgz
      - tar -zxvf allure-$ALLURE_VERSION.tgz -C /opt/
      - ln -s /opt/allure-$ALLURE_VERSION/bin/allure /usr/bin/allure
  build:
    commands:
      - echo "Install python dependencies"
      - python -m pip install --upgrade pip
      - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # - echo "Run tests"
      - echo "Selenium pytest tests"
      - pytest tests --env qa --browser chrome -n 2 -m testDemo1 || true

  post_build:
    commands:
      # 1. Generate HTML report to folder: allure-report
      - allure generate ./allure-results -o ./allure-report --clean
      # 2. Move the allure report to your S3, and replace the bucket name below
      - aws s3 sync ./allure-report s3://allure-report-cheers-255737342472-eu-north-1-an/report-$CODEBUILD_BUILD_NUMBER
      # 3. Print the report URL
      - REPORT_URL="http://allure-report-cheers-255737342472-eu-north-1-an.s3-website.eu-north-1.amazonaws.com/report-$CODEBUILD_BUILD_NUMBER/index.html"
      - echo REPORT_URL
      # 4. Send Slack message with color and button
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDED" = "1" ]; then
          COLOR="#36a64f"
          STATUS="SUCCESS ✅"
        else
          COLOR="#ff0000"
          STATUS="FAILED ❌"
        fi
        
        curl -X POST -H 'Content-type: application/json' --data "{
          \"attachments\": [
            {
              \"color\": \"$COLOR\",
              \"blocks\": [
                {
                  \"type\": \"section\",
                  \"text\": {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*AWS Pipeline Test Report*\n*Project:* $CODEBUILD_BUILD_ID\n*Status:* $STATUS\"
                  }
                },
                {
                  \"type\": \"actions\",
                  \"elements\": [
                    {
                      \"type\": \"button\",
                      \"text\": {
                        \"type\": \"plain_text\",
                        \"text\": \"View Allure Report\"
                      },
                      \"url\": \"$REPORT_URL\",
                      \"style\": \"primary\"
                    }
                  ]
                }
              ]
            }
          ]}" $SLACK_WEBHOOK_URL